Add docker compose and other configurations.
CanastaWiki/Canasta-DockerCompose pull request #2
Opened 2022-04-03 08:52 UTC by amalpaul54111

2022-04-03 09:02 UTC, amalpaul54111 commented
@jeffw16 `./_sources/configs/default.vcl` is used by the varnish container in the `docker-compose.yml`. Or should we just go with the existing location of that file? I would like to hear your opinion on that. 

Should we also add the existing `readme.md` from the **Canasta** repo? 
And the backup scripts would be important too right?
Are there anymore files we could add?

2022-04-05 01:30 UTC, jeffw16 commented
@amalpaul54111 Good catch. Let's copy the `default.vcl` file to here and change that to point to `./configs/default.vcl`.

No need to add the existing README.

Let's not worry about the backups for now. We're going to try to use Restic soon to generate some actual backups.

Let's go ahead and just merge these - you got basically everything. If we need more, I can add them.

Thank you very much Amal, it's really very much appreciated. :)

2022-04-05 01:31 UTC, jeffw16 requested changes

2022-04-05 01:31 UTC, jeffw16 commented on default.vcl
> +vcl 4.0;
Let's move it to under `config/`

2022-04-05 01:31 UTC, jeffw16 commented on docker-compose.yml
> +      - ./default.vcl:/etc/varnish/default.vcl:ro
`./config/default.vcl:/etc/varnish/default.vcl:ro`

2022-04-05 03:27 UTC, amalpaul54111 commented on default.vcl
> +vcl 4.0;
Ok that's good, Done!

2022-04-05 03:28 UTC, amalpaul54111 commented on docker-compose.yml
> +      - ./default.vcl:/etc/varnish/default.vcl:ro
Okay. Done!

2022-04-05 10:02 UTC, jeffw16 approved these changes
LGTM

2022-04-05 10:03 UTC, merged